social:
    resource: "@SocialBundle/Controller/"
    type:     annotation
    prefix:   /

# fos_user:
#     resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile/{id}/{user}
    methods:  [GET, POST]

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile/{id}/{user}



addfriend_show:
    defaults: { _controller: SocialBundle:Profile:showFriend }
    path: /unfollow/{id1}/{user1}/{id}
    methods:  [GET]


addfriend_delete:
    defaults: { _controller: SocialBundle:Profile:delete }
    path: /unfollow/{id1}/{user1}/{id}
    methods:  [GET, DELETE]


fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
