<?php

namespace Social\Bundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AddFriendRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AddFriendRepository extends EntityRepository
{
}
